### ISSUE TITLE
Provide velocity and flows on the cell centres instead of links

### ISSUE THREAD

**Issue by saberraz** [d2hydro/H2i_code_factory#4]
Follow up to https://github.com/d2hydro/H2i_code_factory/issues/1#issuecomment-1022630184 ideally we need to vel/flow on the cell centres (nodes). The averaging used in the previous implementation is no longer valid.

**Comment by maarten-keijzer** [comment]
Yes, we do not have the engine support just yet, but we're planning to create a separate type of result file (.dat) that contains two records for each timestep, first cointaining x-coords, second containing y-coords.

**Comment by d2hydro** [comment]
we have velocity magnitude and direction on the cell centres (nodes) since yesterday. Please find layer upwind velocity in [metadata.json](https://github.com/d2hydro/H2i_code_factory/blob/main/data/de_tol_small/case1/metadata.json). It is indicated as a vector layer. I've updated the [documentation](https://github.com/d2hydro/H2i_code_factory/blob/main/docs/data_format.md#flowsts)

Be aware, the implementation is fresh and under review by H2I.

**Comment by d2hydro** [comment]
resolved by upwind velocity layer (velocityupwind2d.dat). MDAL will only support nodal-data
